name: Build and Deploy Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push API Gateway
      uses: docker/build-push-action@v3
      with:
        context: ./api-gateway
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-api-gateway:latest
    
    - name: Build and push Menu Service
      uses: docker/build-push-action@v3
      with:
        context: ./menu-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-menu-service:latest
    
    - name: Build and push Order Service
      uses: docker/build-push-action@v3
      with:
        context: ./order-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-order-service:latest
    
    - name: Build and push Inventory Service
      uses: docker/build-push-action@v3
      with:
        context: ./inventory-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-inventory-service:latest
    
    - name: Build and push Customer Service
      uses: docker/build-push-action@v3
      with:
        context: ./customer-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-customer-service:latest
    
    - name: Build and push Payment Service
      uses: docker/build-push-action@v3
      with:
        context: ./payment-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cafe-payment-service:latest