name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/cafe

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-api-gateway:latest
            ghcr.io/${{ github.repository_owner }}/cafe-api-gateway:${{ github.sha }}

      - name: Build and push Menu Services
        uses: docker/build-push-action@v5
        with:
          context: ./menu-services
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-menu-services:latest
            ghcr.io/${{ github.repository_owner }}/cafe-menu-services:${{ github.sha }}

      - name: Build and push Order Services
        uses: docker/build-push-action@v5
        with:
          context: ./order-services
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-order-services:latest
            ghcr.io/${{ github.repository_owner }}/cafe-order-services:${{ github.sha }}

      - name: Build and push Inventory Services
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-services
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-inventory-services:latest
            ghcr.io/${{ github.repository_owner }}/cafe-inventory-services:${{ github.sha }}

      - name: Build and push Customer Services
        uses: docker/build-push-action@v5
        with:
          context: ./customer-services
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-customer-services:latest
            ghcr.io/${{ github.repository_owner }}/cafe-customer-services:${{ github.sha }}

      - name: Build and push Payment Services
        uses: docker/build-push-action@v5
        with:
          context: ./payment-services
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cafe-payment-services:latest
            ghcr.io/${{ github.repository_owner }}/cafe-payment-services:${{ github.sha }}
